/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloAdministracion;

import ModuloAdministracion.Interfaz.IBloqueoNegocio;
import ModuloAdministracion.Interfaz.ICarreraNegocio;
import ModuloAdministracion.Interfaz.IComputadoraNegocio;
import ModuloAdministracion.Interfaz.IEstudianteNegocio;
import ModuloAdministracion.Interfaz.IInstitutoNegocio;
import ModuloAdministracion.Interfaz.ILaboratorioNegocio;
import ModuloReservas.Interfaz.IReservaNegocio;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Knocmare
 */
public class frmMenuAdministrativo extends javax.swing.JFrame {
    private final ILaboratorioNegocio laboratorioNegocio;
    private final IInstitutoNegocio institutoNegocio;
    private final IEstudianteNegocio estudianteNegocio;
    private final IComputadoraNegocio computadoraNegocio;
    private final ICarreraNegocio carreraNegocio;
    private final IBloqueoNegocio bloqueoNegocio;
    private final IReservaNegocio reservaNegocio;
    
    /**
     * Creates new form frmLoginPresentacion
     * @param laboratorioNegocio
     * @param institutoNegocio
     * @param estudianteNegocio
     * @param computadoraNegocio
     * @param carreraNegocio
     * @param bloqueoNegocio
     */
    public frmMenuAdministrativo(ILaboratorioNegocio laboratorioNegocio, 
            IInstitutoNegocio institutoNegocio, IEstudianteNegocio estudianteNegocio, 
            IComputadoraNegocio computadoraNegocio, ICarreraNegocio carreraNegocio, 
            IBloqueoNegocio bloqueoNegocio,IReservaNegocio reservaNegocio) {
        this.laboratorioNegocio = laboratorioNegocio;
        this.institutoNegocio = institutoNegocio;
        this.estudianteNegocio = estudianteNegocio;
        this.computadoraNegocio = computadoraNegocio;
        this.carreraNegocio = carreraNegocio;
        this.bloqueoNegocio = bloqueoNegocio;
        this.reservaNegocio = reservaNegocio;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCambiante = new javax.swing.JPanel();
        jPanelPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEstudiantes = new javax.swing.JMenu();
        OpcionEstudiantesListado = new javax.swing.JMenuItem();
        jMenuCarreras = new javax.swing.JMenu();
        OpcionCarrerasListado = new javax.swing.JMenuItem();
        jMenuComputadoras = new javax.swing.JMenu();
        OpcionComputadorasListado = new javax.swing.JMenuItem();
        jMenuBloqueos = new javax.swing.JMenu();
        OpcionBloqueosListado = new javax.swing.JMenuItem();
        jMenuLaboratorio = new javax.swing.JMenu();
        OpcionLaboratoriosListado = new javax.swing.JMenuItem();
        jMenuInstituto = new javax.swing.JMenu();
        OpcionInstitutosListado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelCambiante.setBackground(new java.awt.Color(35, 35, 35));
        jPanelCambiante.setPreferredSize(new java.awt.Dimension(1920, 1041));

        jPanelPantalla.setBackground(new java.awt.Color(54, 54, 54));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 96)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administración CISCO");

        javax.swing.GroupLayout jPanelPantallaLayout = new javax.swing.GroupLayout(jPanelPantalla);
        jPanelPantalla.setLayout(jPanelPantallaLayout);
        jPanelPantallaLayout.setHorizontalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        jPanelPantallaLayout.setVerticalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCambianteLayout = new javax.swing.GroupLayout(jPanelCambiante);
        jPanelCambiante.setLayout(jPanelCambianteLayout);
        jPanelCambianteLayout.setHorizontalGroup(
            jPanelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCambianteLayout.setVerticalGroup(
            jPanelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambianteLayout.createSequentialGroup()
                .addComponent(jPanelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 853, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuEstudiantes.setText("Estudiantes");
        jMenuEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionEstudiantesListado.setText("Lista de Estudiantes");
        OpcionEstudiantesListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionEstudiantesListadoActionPerformed(evt);
            }
        });
        jMenuEstudiantes.add(OpcionEstudiantesListado);

        jMenuBar1.add(jMenuEstudiantes);

        jMenuCarreras.setText("Carreras");
        jMenuCarreras.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionCarrerasListado.setText("Lista de Carreras");
        OpcionCarrerasListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionCarrerasListadoActionPerformed(evt);
            }
        });
        jMenuCarreras.add(OpcionCarrerasListado);

        jMenuBar1.add(jMenuCarreras);

        jMenuComputadoras.setText("Computadoras");
        jMenuComputadoras.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionComputadorasListado.setText("Lista de Computaros");
        OpcionComputadorasListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionComputadorasListadoActionPerformed(evt);
            }
        });
        jMenuComputadoras.add(OpcionComputadorasListado);

        jMenuBar1.add(jMenuComputadoras);

        jMenuBloqueos.setText("Bloqueos");
        jMenuBloqueos.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionBloqueosListado.setText("Lista de Bloqueos");
        OpcionBloqueosListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionBloqueosListadoActionPerformed(evt);
            }
        });
        jMenuBloqueos.add(OpcionBloqueosListado);

        jMenuBar1.add(jMenuBloqueos);

        jMenuLaboratorio.setText("Laboratorio");
        jMenuLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionLaboratoriosListado.setText("Lista de Laboratorios");
        OpcionLaboratoriosListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionLaboratoriosListadoActionPerformed(evt);
            }
        });
        jMenuLaboratorio.add(OpcionLaboratoriosListado);

        jMenuBar1.add(jMenuLaboratorio);

        jMenuInstituto.setText("Instituto");
        jMenuInstituto.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        OpcionInstitutosListado.setText("Lista de Institutos");
        OpcionInstitutosListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionInstitutosListadoActionPerformed(evt);
            }
        });
        jMenuInstituto.add(OpcionInstitutosListado);

        jMenuBar1.add(jMenuInstituto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionEstudiantesListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionEstudiantesListadoActionPerformed
        panelEstudiantesListado panelEstudiante = new panelEstudiantesListado(estudianteNegocio, carreraNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelEstudiante, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionEstudiantesListadoActionPerformed

    private void OpcionCarrerasListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionCarrerasListadoActionPerformed
        panelCarrerasListado panelCarrera = new panelCarrerasListado(carreraNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelCarrera, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionCarrerasListadoActionPerformed

    private void OpcionComputadorasListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionComputadorasListadoActionPerformed
        panelComputadorasListado panelComputadora = new panelComputadorasListado(computadoraNegocio,carreraNegocio, laboratorioNegocio,reservaNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelComputadora, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionComputadorasListadoActionPerformed

    private void OpcionBloqueosListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionBloqueosListadoActionPerformed
        panelBloqueosListado panelBloqueo = new panelBloqueosListado(bloqueoNegocio, estudianteNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelBloqueo, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionBloqueosListadoActionPerformed

    private void OpcionLaboratoriosListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionLaboratoriosListadoActionPerformed
        panelLaboratoriosListado panelLaboratorio = new panelLaboratoriosListado(laboratorioNegocio, institutoNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelLaboratorio, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionLaboratoriosListadoActionPerformed

    private void OpcionInstitutosListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionInstitutosListadoActionPerformed
        panelInstitutosListado panelInstituto = new panelInstitutosListado(institutoNegocio,laboratorioNegocio);
        jPanelCambiante.setLayout(new BorderLayout());
        jPanelCambiante.removeAll();
        jPanelCambiante.add(panelInstituto, BorderLayout.CENTER);
        jPanelCambiante.revalidate();
        jPanelCambiante.repaint();
    }//GEN-LAST:event_OpcionInstitutosListadoActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OpcionBloqueosListado;
    private javax.swing.JMenuItem OpcionCarrerasListado;
    private javax.swing.JMenuItem OpcionComputadorasListado;
    private javax.swing.JMenuItem OpcionEstudiantesListado;
    private javax.swing.JMenuItem OpcionInstitutosListado;
    private javax.swing.JMenuItem OpcionLaboratoriosListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBloqueos;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuComputadoras;
    private javax.swing.JMenu jMenuEstudiantes;
    private javax.swing.JMenu jMenuInstituto;
    private javax.swing.JMenu jMenuLaboratorio;
    private javax.swing.JPanel jPanelCambiante;
    private javax.swing.JPanel jPanelPantalla;
    // End of variables declaration//GEN-END:variables
}
