/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloReservas;

import DTOs.ComputadoraDTO;
import Excepcion.NegocioException;
import ModuloAdministracion.Interfaz.IComputadoraDAO;
import ModuloReservas.util.ComputadoraPanel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JFrame;

/**
 *
 * @author gaspa
 */
public class FrmConfirmarReserva extends javax.swing.JFrame {
    private final ComputadoraDTO computadora;
    private IComputadoraDAO computadoraDAO;
    private FrmReservas frmReservas;
    private String idUsuario;
    private String minutos;
    
    /**
     * Creates new form FrmConfirmarReserva
     * @param computadora
     */
    public FrmConfirmarReserva(ComputadoraDTO computadora,IComputadoraDAO computadoraDAO, String idUsuario, String minutos,FrmReservas frmReservas) {
        this.computadora = computadora;
        this.frmReservas = frmReservas;
        this.computadoraDAO = computadoraDAO;
        this.idUsuario = idUsuario;
        this.minutos = minutos;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        this.computadorasPanel.setLayout(new BoxLayout(this.computadorasPanel, BoxLayout.X_AXIS));
        
        this.cargarComputadora();
    }
    
    public void cargarComputadora(){
        this.computadorasPanel.removeAll();
        this.computadorasPanel.repaint();
        
        ComputadoraPanel panel = new ComputadoraPanel(computadora,computadoraDAO,idUsuario,minutos,false,frmReservas);
        this.computadorasPanel.add(panel);
        
        this.estudianteLabel.setText("Estudiante: "+idUsuario);
        this.tiempoLabel.setText("Tiempo: "+minutos+" minutos");
        this.numeroEquipoLabel.setText("Equipo numero: "+computadora.getNumeroMaquina().toString());
        this.SoftwareLabel.setText("Software del equipo: "+computadora.getCarrera().getNombreCarrera());
        this.revalidate();
        this.repaint();
    }
    private void volver() {
        frmReservas.habilitarVentana();
        frmReservas.setVentanaReservaAbierta(false); // Reset del flag
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        computadorasPanel = new javax.swing.JPanel();
        numeroEquipoLabel = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        SoftwareLabel = new javax.swing.JLabel();
        estudianteLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        confirmarBTN = new javax.swing.JButton();
        cancelarBTN = new javax.swing.JButton();
        carrerasBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(47, 47, 47));

        jPanel2.setBackground(new java.awt.Color(86, 86, 86));

        computadorasPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout computadorasPanelLayout = new javax.swing.GroupLayout(computadorasPanel);
        computadorasPanel.setLayout(computadorasPanelLayout);
        computadorasPanelLayout.setHorizontalGroup(
            computadorasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        computadorasPanelLayout.setVerticalGroup(
            computadorasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        numeroEquipoLabel.setBackground(new java.awt.Color(255, 255, 255));
        numeroEquipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numeroEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroEquipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroEquipoLabel.setText("Equipo Numero: ");

        tiempoLabel.setBackground(new java.awt.Color(255, 255, 255));
        tiempoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tiempoLabel.setForeground(new java.awt.Color(255, 255, 255));
        tiempoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoLabel.setText("Tiempo:");

        SoftwareLabel.setBackground(new java.awt.Color(255, 255, 255));
        SoftwareLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SoftwareLabel.setForeground(new java.awt.Color(255, 255, 255));
        SoftwareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SoftwareLabel.setText("Software del equipo:");

        estudianteLabel.setBackground(new java.awt.Color(255, 255, 255));
        estudianteLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estudianteLabel.setForeground(new java.awt.Color(255, 255, 255));
        estudianteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estudianteLabel.setText("Estudiante:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiempoLabel)
                    .addComponent(computadorasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(547, 547, 547))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SoftwareLabel)
                    .addComponent(numeroEquipoLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(estudianteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(computadorasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tiempoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroEquipoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SoftwareLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estudianteLabel)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirme su seleccion");

        confirmarBTN.setBackground(new java.awt.Color(86, 86, 86));
        confirmarBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        confirmarBTN.setForeground(new java.awt.Color(255, 255, 255));
        confirmarBTN.setText("Confirmar");
        confirmarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBTNActionPerformed(evt);
            }
        });

        cancelarBTN.setBackground(new java.awt.Color(86, 86, 86));
        cancelarBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cancelarBTN.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBTN.setText("Cancelar");
        cancelarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTNActionPerformed(evt);
            }
        });

        carrerasBTN.setBackground(new java.awt.Color(86, 86, 86));
        carrerasBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        carrerasBTN.setForeground(new java.awt.Color(255, 255, 255));
        carrerasBTN.setText("Carreras");
        carrerasBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrerasBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(carrerasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(carrerasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarBTNActionPerformed

    private void cancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTNActionPerformed
        this.volver();
        
    }//GEN-LAST:event_cancelarBTNActionPerformed

    private void carrerasBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrerasBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carrerasBTNActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SoftwareLabel;
    private javax.swing.JButton cancelarBTN;
    private javax.swing.JButton carrerasBTN;
    private javax.swing.JPanel computadorasPanel;
    private javax.swing.JButton confirmarBTN;
    private javax.swing.JLabel estudianteLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numeroEquipoLabel;
    private javax.swing.JLabel tiempoLabel;
    // End of variables declaration//GEN-END:variables
}
